# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20934d7448089aa0e43e9a1ff439e31d29efeecae7cfdcea11214e970a378c566d2b86abb0dfd9287d2a3759cca433d04079100bdced50f2373efc6f055924e9

test:
  secret_key_base: 4eacc3a3cb1c31edc0f0d597bf3d59df3b5bbebf366dc70865a742fab56a42ccdaca04e590c7e6ab8111cfd9c56b7c3e07d36b4008a3ab0aaf1910c369236078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
